Feature/edit usuario
ic0045/eventscomp pull request #59
Opened 2023-06-01 17:26 UTC by cristh1an

2023-06-01 17:41 UTC, viniciustrindade requested changes
Verifica os comentários

2023-06-01 17:41 UTC, viniciustrindade commented on src/pages/auth/cadastro.tsx
> +    const res = await fetch(`${apiURL}/api/admin/usuarios?id=${session.user.id}`);
Não use a api admin, vc pode usar a o auth.getDetailedSession ou criar um metodo em auth pra pegar o usuario completo. 

Alem disso a api administrativa tem uma falha de segurança. Ela ta aberta sem autenticacao. Dessa forma vou precisar colocar na api a restrição de somente administradores poderem consultar.

2023-06-01 23:09 UTC, cristh1an commented
feito.

2023-06-04 18:21 UTC, viniciustrindade approved these changes

2023-06-04 18:21 UTC, viniciustrindade commented on src/apis/UsuarioAPI.ts
> +        const response = await fetch(`${this.apiURL}/admin/usuarios?id=${usuario.id}`, {
As rotas pra edicao do usuario nao devem usar as rotas administrativas "/admin/
Criar uma rota "private" na api chamando `${this.apiURL}/private/usuarios?id=${usuario.id}` e deixa a rota /admin somente pros formularios administrativos. 
nessa rota private/[resource]/index.ts adicione o useServerSession no inicio e pegue o usuario logado por la e verifica se o id do usuario logado é o mesmo id do usuario que ele ta tentando modificar.. se for diferente dispre um erro de permissão negada.

2023-06-04 18:21 UTC, viniciustrindade commented on src/apis/UsuarioAPI.ts
> +        const response = await fetch(`${this.apiURL}/admin/usuarios?id=${usuario.id}`, {
@cristh1an

2023-06-04 18:22 UTC, merged